version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 728738226157.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t rohit .
      - docker tag rohit:latest 728738226157.dkr.ecr.us-east-1.amazonaws.com/rohit:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing....
      - docker push 728738226157.dkr.ecr.us-east-1.amazonaws.com/rohit:latest
